<?php
///vagrant/
///vagrant/wp-admin/
///vagrant/wp-admin/css/
///vagrant/wp-admin/css/colors/
///vagrant/wp-admin/css/colors/blue/
///vagrant/wp-admin/css/colors/coffee/
///vagrant/wp-admin/css/colors/ectoplasm/
///vagrant/wp-admin/css/colors/light/
///vagrant/wp-admin/css/colors/midnight/
///vagrant/wp-admin/css/colors/ocean/
///vagrant/wp-admin/css/colors/sunrise/
///vagrant/wp-admin/images/
///vagrant/wp-admin/includes/
///vagrant/wp-admin/js/
///vagrant/wp-admin/maint/
///vagrant/wp-admin/network/
///vagrant/wp-admin/user/
///vagrant/wp-content/
///vagrant/wp-content/plugins/
///vagrant/wp-content/plugins/js_composer/
///vagrant/wp-content/plugins/js_composer/assets/
///vagrant/wp-content/plugins/js_composer/assets/css/
///vagrant/wp-content/plugins/js_composer/assets/css/lib/
///vagrant/wp-content/plugins/js_composer/assets/css/ui-custom-theme/
///vagrant/wp-content/plugins/js_composer/assets/css/ui-custom-theme/images/
///vagrant/wp-content/plugins/js_composer/assets/css/ui-custom-theme/less/
///vagrant/wp-content/plugins/js_composer/assets/images/
///vagrant/wp-content/plugins/js_composer/assets/images/icons/
///vagrant/wp-content/plugins/js_composer/assets/js/
///vagrant/wp-content/plugins/js_composer/assets/js/backend/
///vagrant/wp-content/plugins/js_composer/assets/js/editors/
///vagrant/wp-content/plugins/js_composer/assets/js/frontend_editor/
///vagrant/wp-content/plugins/js_composer/assets/js/frontend_editor/vendors/
///vagrant/wp-content/plugins/js_composer/assets/js/frontend_editor/vendors/plugins/
///vagrant/wp-content/plugins/js_composer/assets/js/params/
///vagrant/wp-content/plugins/js_composer/assets/js/vendors/
///vagrant/wp-content/plugins/js_composer/assets/less/
///vagrant/wp-content/plugins/js_composer/assets/less/backend_shortcodes/
///vagrant/wp-content/plugins/js_composer/assets/less/config/
///vagrant/wp-content/plugins/js_composer/assets/less/lib/
///vagrant/wp-content/plugins/js_composer/assets/less/modules/
///vagrant/wp-content/plugins/js_composer/assets/less/params/
///vagrant/wp-content/plugins/js_composer/assets/less/popups/
///vagrant/wp-content/plugins/js_composer/assets/less/settings_tabs/
///vagrant/wp-content/plugins/js_composer/assets/less/shortcodes/
///vagrant/wp-content/plugins/js_composer/assets/less/vendor/
///vagrant/wp-content/plugins/js_composer/assets/lib/
///vagrant/wp-content/plugins/js_composer/assets/lib/ace-builds/
///vagrant/wp-content/plugins/js_composer/assets/lib/ace-builds/src-min-noconflict/
///vagrant/wp-content/plugins/js_composer/assets/lib/autosuggest/
///vagrant/wp-content/plugins/js_composer/assets/lib/bootstrap3/
///vagrant/wp-content/plugins/js_composer/assets/lib/bootstrap3/dist/
///vagrant/wp-content/plugins/js_composer/assets/lib/bootstrap3/dist/js/
///vagrant/wp-content/plugins/js_composer/assets/lib/bootstrap3/less/
///vagrant/wp-content/plugins/js_composer/assets/lib/bootstrap3/less/mixins/
///vagrant/wp-content/plugins/js_composer/assets/lib/flexslider/
///vagrant/wp-content/plugins/js_composer/assets/lib/flexslider/fonts/
///vagrant/wp-content/plugins/js_composer/assets/lib/flexslider/images/
///vagrant/wp-content/plugins/js_composer/assets/lib/isotope/
///vagrant/wp-content/plugins/js_composer/assets/lib/isotope/dist/
///vagrant/wp-content/plugins/js_composer/assets/lib/jcarousellite/
///vagrant/wp-content/plugins/js_composer/assets/lib/jquery-ui-tabs-rotate/
///vagrant/wp-content/plugins/js_composer/assets/lib/jquery-waypoints/
///vagrant/wp-content/plugins/js_composer/assets/lib/json-js/
///vagrant/wp-content/plugins/js_composer/assets/lib/nivoslider/
///vagrant/wp-content/plugins/js_composer/assets/lib/nivoslider/themes/
///vagrant/wp-content/plugins/js_composer/assets/lib/nivoslider/themes/bar/
///vagrant/wp-content/plugins/js_composer/assets/lib/nivoslider/themes/dark/
///vagrant/wp-content/plugins/js_composer/assets/lib/nivoslider/themes/default/
///vagrant/wp-content/plugins/js_composer/assets/lib/nivoslider/themes/light/
///vagrant/wp-content/plugins/js_composer/assets/lib/php.default/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/css/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/images/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/images/prettyPhoto/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/images/prettyPhoto/dark_rounded/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/images/prettyPhoto/dark_square/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/images/prettyPhoto/default/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/images/prettyPhoto/facebook/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/images/prettyPhoto/light_rounded/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/images/prettyPhoto/light_square/
///vagrant/wp-content/plugins/js_composer/assets/lib/prettyphoto/js/
///vagrant/wp-content/plugins/js_composer/assets/lib/progress-circle/
///vagrant/wp-content/plugins/js_composer/assets/lib/scrollTo/
///vagrant/wp-content/plugins/js_composer/assets/lib/vc_carousel/
///vagrant/wp-content/plugins/js_composer/assets/lib/vc_carousel/css/
///vagrant/wp-content/plugins/js_composer/assets/lib/vc_carousel/fonts/
///vagrant/wp-content/plugins/js_composer/assets/lib/vc_carousel/js/
///vagrant/wp-content/plugins/js_composer/assets/lib/vc_chart/
///vagrant/wp-content/plugins/js_composer/assets/vc/
///vagrant/wp-content/plugins/js_composer/assets/vc/3rd-party/
///vagrant/wp-content/plugins/js_composer/assets/vc/elements_icons/
///vagrant/wp-content/plugins/js_composer/assets/vc/fe/
///vagrant/wp-content/plugins/js_composer/assets/vc/fe/row_layouts/
///vagrant/wp-content/plugins/js_composer/assets/vc/fe/screen_sizes/
///vagrant/wp-content/plugins/js_composer/assets/vc/fe/social/
///vagrant/wp-content/plugins/js_composer/assets/vc/fe/social/fb/
///vagrant/wp-content/plugins/js_composer/assets/vc/fe/social/gp/
///vagrant/wp-content/plugins/js_composer/assets/vc/fe/social/pinterest/
///vagrant/wp-content/plugins/js_composer/assets/vc/fe/social/tw/
///vagrant/wp-content/plugins/js_composer/assets/vc/logo/
///vagrant/wp-content/plugins/js_composer/assets/vc/row_layouts/
///vagrant/wp-content/plugins/js_composer/assets/vc/templates/
///vagrant/wp-content/plugins/js_composer/config/
///vagrant/wp-content/plugins/js_composer/include/
///vagrant/wp-content/plugins/js_composer/include/classes/
///vagrant/wp-content/plugins/js_composer/include/classes/core/
///vagrant/wp-content/plugins/js_composer/include/classes/editors/
///vagrant/wp-content/plugins/js_composer/include/classes/editors/navbar/
///vagrant/wp-content/plugins/js_composer/include/classes/editors/popups/
///vagrant/wp-content/plugins/js_composer/include/classes/settings/
///vagrant/wp-content/plugins/js_composer/include/classes/shortcodes/
///vagrant/wp-content/plugins/js_composer/include/classes/updaters/
///vagrant/wp-content/plugins/js_composer/include/classes/vendors/
///vagrant/wp-content/plugins/js_composer/include/classes/vendors/plugins/
///vagrant/wp-content/plugins/js_composer/include/helpers/
///vagrant/wp-content/plugins/js_composer/include/params/
///vagrant/wp-content/plugins/js_composer/include/params/colorpicker/
///vagrant/wp-content/plugins/js_composer/include/params/column_offset/
///vagrant/wp-content/plugins/js_composer/include/params/css_editor/
///vagrant/wp-content/plugins/js_composer/include/params/font_container/
///vagrant/wp-content/plugins/js_composer/include/params/google_fonts/
///vagrant/wp-content/plugins/js_composer/include/params/href/
///vagrant/wp-content/plugins/js_composer/include/params/loop/
///vagrant/wp-content/plugins/js_composer/include/params/options/
///vagrant/wp-content/plugins/js_composer/include/params/sorted_list/
///vagrant/wp-content/plugins/js_composer/include/params/tab_id/
///vagrant/wp-content/plugins/js_composer/include/params/textarea_html/
///vagrant/wp-content/plugins/js_composer/include/params/vc_link/
///vagrant/wp-content/plugins/js_composer/include/templates/
///vagrant/wp-content/plugins/js_composer/include/templates/editors/
///vagrant/wp-content/plugins/js_composer/include/templates/editors/navbar/
///vagrant/wp-content/plugins/js_composer/include/templates/editors/partials/
///vagrant/wp-content/plugins/js_composer/include/templates/editors/popups/
///vagrant/wp-content/plugins/js_composer/include/templates/params/
///vagrant/wp-content/plugins/js_composer/include/templates/params/column_offset/
///vagrant/wp-content/plugins/js_composer/include/templates/params/google_fonts/
///vagrant/wp-content/plugins/js_composer/include/templates/params/loop/
///vagrant/wp-content/plugins/js_composer/include/templates/params/options/
///vagrant/wp-content/plugins/js_composer/include/templates/shortcodes/
///vagrant/wp-content/plugins/js_composer/include/templates/shortcodes/post_block/
///vagrant/wp-content/plugins/js_composer/locale/
///vagrant/wp-content/plugins/wordpress-importer/
///vagrant/wp-content/plugins/wordpress-importer/languages/
///vagrant/wp-content/plugins/wp-retina-2x/
///vagrant/wp-content/plugins/wp-retina-2x/img/
///vagrant/wp-content/plugins/wp-retina-2x/inc/
///vagrant/wp-content/plugins/wp-retina-2x/js/
///vagrant/wp-content/plugins/wp-retina-2x/languages/
///vagrant/wp-content/uploads/
///vagrant/wp-content/uploads/backwpup-e424d1-logs/
///vagrant/wp-content/uploads/redux/
///vagrant/wp-content/uploads/redux/google-fonts/
///vagrant/wp-includes/
///vagrant/wp-includes/ID3/
///vagrant/wp-includes/SimplePie/
///vagrant/wp-includes/SimplePie/Cache/
///vagrant/wp-includes/SimplePie/Content/
///vagrant/wp-includes/SimplePie/Content/Type/
///vagrant/wp-includes/SimplePie/Decode/
///vagrant/wp-includes/SimplePie/Decode/HTML/
///vagrant/wp-includes/SimplePie/HTTP/
///vagrant/wp-includes/SimplePie/Net/
///vagrant/wp-includes/SimplePie/Parse/
///vagrant/wp-includes/SimplePie/XML/
///vagrant/wp-includes/SimplePie/XML/Declaration/
///vagrant/wp-includes/Text/
///vagrant/wp-includes/Text/Diff/
///vagrant/wp-includes/Text/Diff/Engine/
///vagrant/wp-includes/Text/Diff/Renderer/
///vagrant/wp-includes/certificates/
///vagrant/wp-includes/css/
///vagrant/wp-includes/fonts/
///vagrant/wp-includes/images/
///vagrant/wp-includes/images/crystal/
///vagrant/wp-includes/images/media/
///vagrant/wp-includes/images/smilies/
///vagrant/wp-includes/images/wlw/
///vagrant/wp-includes/js/
///vagrant/wp-includes/js/crop/
///vagrant/wp-includes/js/imgareaselect/
///vagrant/wp-includes/js/jcrop/
///vagrant/wp-includes/js/jquery/
///vagrant/wp-includes/js/jquery/ui/
///vagrant/wp-includes/js/mediaelement/
///vagrant/wp-includes/js/plupload/
///vagrant/wp-includes/js/swfupload/
///vagrant/wp-includes/js/swfupload/plugins/
///vagrant/wp-includes/js/thickbox/
///vagrant/wp-includes/js/tinymce/
///vagrant/wp-includes/js/tinymce/langs/
///vagrant/wp-includes/js/tinymce/plugins/
///vagrant/wp-includes/js/tinymce/plugins/charmap/
///vagrant/wp-includes/js/tinymce/plugins/colorpicker/
///vagrant/wp-includes/js/tinymce/plugins/compat3x/
///vagrant/wp-includes/js/tinymce/plugins/compat3x/css/
///vagrant/wp-includes/js/tinymce/plugins/directionality/
///vagrant/wp-includes/js/tinymce/plugins/fullscreen/
///vagrant/wp-includes/js/tinymce/plugins/hr/
///vagrant/wp-includes/js/tinymce/plugins/image/
///vagrant/wp-includes/js/tinymce/plugins/lists/
///vagrant/wp-includes/js/tinymce/plugins/media/
///vagrant/wp-includes/js/tinymce/plugins/paste/
///vagrant/wp-includes/js/tinymce/plugins/tabfocus/
///vagrant/wp-includes/js/tinymce/plugins/textcolor/
///vagrant/wp-includes/js/tinymce/plugins/wordpress/
///vagrant/wp-includes/js/tinymce/plugins/wpautoresize/
///vagrant/wp-includes/js/tinymce/plugins/wpdialogs/
///vagrant/wp-includes/js/tinymce/plugins/wpeditimage/
///vagrant/wp-includes/js/tinymce/plugins/wpfullscreen/
///vagrant/wp-includes/js/tinymce/plugins/wpgallery/
///vagrant/wp-includes/js/tinymce/plugins/wplink/
///vagrant/wp-includes/js/tinymce/plugins/wpview/
///vagrant/wp-includes/js/tinymce/skins/
///vagrant/wp-includes/js/tinymce/skins/lightgray/
///vagrant/wp-includes/js/tinymce/skins/lightgray/fonts/
///vagrant/wp-includes/js/tinymce/skins/lightgray/img/
///vagrant/wp-includes/js/tinymce/skins/wordpress/
///vagrant/wp-includes/js/tinymce/skins/wordpress/images/
///vagrant/wp-includes/js/tinymce/themes/
///vagrant/wp-includes/js/tinymce/themes/modern/
///vagrant/wp-includes/js/tinymce/utils/
///vagrant/wp-includes/pomo/
///vagrant/wp-includes/theme-compat/
